### ISSUE TITLE
Compared to sass / scss

### ISSUE THREAD

**Issue by jcward** [ncannasse/hss#16]
I am curious what the pros / cons are vs sass. Seems like hss could compile faster and perhaps be (arguably?) more easy to use across platforms (though [libsass](https://github.com/sass/libsass) + [sassc](https://github.com/sass/sassc) provides a fast native implementation.)

 Are there other advantages I didn't notice?

Note: sass doesn't allow vars to be blocks, but it does allow "mixins" which are the same behavior (reusable sets of behaviors.) And mixins can also be parametric (e.g. a block with local parameters), which is slick for defining parametric behaviors. Perhaps that is `@include`? I need to read closer...

**Comment by R32** [comment]
pros: no idea, I use it just because I'm learning OCaml. the nml is also a functional language. :smile: 

cons:  hss supports limited rules, many standard css attributes/values (especially css3) will be treated as syntax errors, which is very annoying. Actually it's really hard to find the right syntax to match all the attribute values.

about "mixins":  since hss supports block variables, So the the Block Variable can actually easily add features similar to functions.

**Comment by jcward** [comment]
Awesome, good to know. I also didn't notice this was an older repo (with just some newer work on it.) I'll go ahead and close this.
